# @author: Vikram Somavaram
image: node:6.12.0

stages:
  - lint
  - build
  - release
  - review
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}/${CI_BUILD_REF_NAME}:${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY_IMAGE}/${CI_BUILD_REF_NAME}:latest
  CONTAINER_IMAGE_UNTAGGED: ${CI_REGISTRY_IMAGE}/${CI_BUILD_REF_NAME}
  DOCKER_DRIVER: overlay2
  REGION: ap-south-1
  REPOSITORY_URL: 874146190074.dkr.ecr.ap-south-1.amazonaws.com/lms-sso

cache:
  paths:
    - node_modules/
    - build/

lint:
  stage: lint
  script:
    - npm install -g yarn
    - yarn install
    - yarn run lint
  only:
    - master
    - development
    - qa
    - uat

build:
  stage: build
  artifacts:
    paths:
      - node_modules/
      - build/
  script:
    - npm install -g yarn
    - yarn install
    - yarn run build -- --release
  only:
    - development
    - qa
    - master
    - uat
    
release:
  stage: release
  image: docker:latest
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_DRIVER: "overlay2"
    DOCKER_HOST: "tcp://localhost:2375"
  before_script:
    - docker info
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - echo "Building image..."
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}
    - $(aws ecr get-login --no-include-email --region "${REGION}")
    - echo "Tagging image for ECR..."
    - docker tag ${CONTAINER_IMAGE_LATEST} ${REPOSITORY_URL}:${IMAGE_TAG}
    - docker tag ${CONTAINER_IMAGE_LATEST} ${REPOSITORY_URL}:latest
    - echo "Pushing image to ECR..."
    - docker push ${REPOSITORY_URL}:latest
    - docker push ${REPOSITORY_URL}:${IMAGE_TAG}
  only:
    - development
    - qa
    - master

deploy-dev:

release-uat:
  stage: release
  image: docker:latest
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_DRIVER: "overlay2"
    DOCKER_HOST: "tcp://localhost:2375"
  before_script:
    - docker info
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - IMAGE_TAG="$CI_COMMIT_SHORT_SHA"
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - echo "Building image..."
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}
    - $(aws ecr get-login --no-include-email --region "${REGION}")
    - echo "Tagging image for ECR..."
    - docker tag ${CONTAINER_IMAGE_LATEST} ${REPOSITORY_URL}:${IMAGE_TAG}
    - docker tag ${CONTAINER_IMAGE_LATEST} ${REPOSITORY_URL}:uat
    - echo "Pushing image to ECR..."
    - docker push ${REPOSITORY_URL}:uat
    - docker push ${REPOSITORY_URL}:${IMAGE_TAG}
  only:
    - uat

deploy-dev:
  stage: deploy
  image: docker:latest
  services:
    - docker:18.09.7-dind
  before_script:
    # Install python requirements
    - apk update
    - apk upgrade
    - apk add util-linux pciutils usbutils coreutils binutils findutils grep
    - apk add python python-dev py-pip
     # Install awscli
    - pip install awscli
  script:
    - cd ecs-task-def
     # Update task and service
    - aws ecs register-task-definition --region ${REGION} --cli-input-json file://deploy-ecs.json >> temp.json
    - REV=`grep  '"revision"' temp.json | awk '{print $2}'`
    - echo $REV
    - aws ecs update-service --cluster Rankguru-Dev --service lms-sso-dev-service --task-definition lms-sso-dev-tdf:${REV} --region ${REGION}  
  only:
    - development

deploy-uat:
  stage: deploy
  image: docker:latest
  services:
    - docker:18.09.7-dind
  before_script:
    # Install python requirements
    - apk update
    - apk upgrade
    - apk add util-linux pciutils usbutils coreutils binutils findutils grep
    - apk add python python-dev py-pip
     # Install awscli
    - pip install awscli
  script:
    - cd ecs-task-def
     # Update task and service
    - aws ecs register-task-definition --region ${REGION} --cli-input-json file://deploy-ecs.json >> temp.json
    - REV=`grep  '"revision"' temp.json | awk '{print $2}'`
    - echo $REV
    - aws ecs update-service --cluster Rankguru-Dev --service lms-sso-dev-service --task-definition lms-sso-dev-tdf:${REV} --region ${REGION}  
  only:
    - development
    - aws ecs register-task-definition --region ${REGION} --cli-input-json file://deploy-ecs-uat.json >> temp.json
    - REV=`grep  '"revision"' temp.json | awk '{print $2}'`
    - echo $REV
    - aws ecs update-service --cluster Rankguru-UAT --service lms-sso-UAT-service --task-definition lms-sso-UAT-tdf:${REV} --region ${REGION}  
  only:
    - uat
    
# deploy-dev:
#   stage: deploy
#   image: arbaz7/gcloud-kubectl-helm:latest
#   services:
#     - docker:18.09.7-dind
#   before_script:
#     - mkdir -p /etc/deploy
#     - echo ${kube_config} > kube_config
#     - base64 -d kube_config > ${KUBECONFIG}
#     - echo ${gcloud_auth} > gcloud_auth.base64
#     - base64 -d gcloud_auth.base64 > gcloud_auth.json
#     # - kubectl config use-context gke_egnify-product_us-central1-a_hydra-federation
#     - helm init --client-only
#     - helm repo update
#     - gcloud auth activate-service-account --key-file=gcloud_auth.json
#     - gcloud container clusters get-credentials hydra-federation-dev --zone asia-south1-a --project egnify-product
#   script:
#     - export NAMESPACE=dev;
#     - export RELEASE_NAME=sso-${NAMESPACE}-lms
#     - export DEPLOYS=$(helm ls | grep $RELEASE_NAME | wc -l)
#     - if [ ${DEPLOYS}  -eq 0 ]; then helm install --name=${RELEASE_NAME} charts --set image.tag=${CI_BUILD_REF} -f charts/values/${NAMESPACE}.yaml --namespace=${NAMESPACE}; else helm upgrade ${RELEASE_NAME} charts --set image.tag=${CI_BUILD_REF} -f charts/values/${NAMESPACE}.yaml --namespace=${NAMESPACE}; fi
#   environment:
#     name: dev
#   only:
#     - development

# deploy-qa:
#   stage: deploy
#   image: arbaz7/gcloud-kubectl-helm:latest
#   services:
#     - docker:18.09.7-dind
#   before_script:
#     - mkdir -p /etc/deploy
#     - echo ${kube_config} > kube_config
#     - base64 -d kube_config > ${KUBECONFIG}
#     - echo ${gcloud_auth} > gcloud_auth.base64
#     - base64 -d gcloud_auth.base64 > gcloud_auth.json
#     # - kubectl config use-context gke_egnify-product_us-central1-a_hydra-federation
#     - helm init --client-only
#     - gcloud auth activate-service-account --key-file=gcloud_auth.json
#     - helm repo update
#     - gcloud container clusters get-credentials hydra-federation-dev --zone asia-south1-a --project egnify-product
#   script:
#     - export NAMESPACE=qa;
#     - export RELEASE_NAME=sso-${NAMESPACE}-hydra
#     - export DEPLOYS=$(helm ls | grep $RELEASE_NAME | wc -l)
#     - if [ ${DEPLOYS}  -eq 0 ]; then helm install --name=${RELEASE_NAME} charts --set image.tag=${CI_BUILD_REF} -f charts/values/${NAMESPACE}.yaml --namespace=${NAMESPACE}; else helm upgrade ${RELEASE_NAME} charts --set image.tag=${CI_BUILD_REF} -f charts/values/${NAMESPACE}.yaml --namespace=${NAMESPACE}; fi
#   environment:
#     name: qa
#     # url: https://qa.hydra.egnify.io
#   only:
#     - qa

# deploy-uat:
#   stage: deploy
#   image: google/cloud-sdk:latest
#   services:
#     - docker:18.09.7-dind
#   before_script:
#     - mkdir -p /etc/deploy
#     - echo ${GLOUD_AUTH_DEV} > gcloud_auth.base64
#     - base64 -d gcloud_auth.base64 > gcloud_auth.json
#     - gcloud auth activate-service-account --key-file=gcloud_auth.json
#   script:
#     - export NAMESPACE=uat;
#     - cd build/
#     - gsutil cp gs://hydra-config-dev/config/${CI_PROJECT_NAME}/app.yaml .
#     - gcloud app deploy --project egnify-product --stop-previous-version --promote -q
#   environment:
#     name: uat
#     # url: https://qa.hydra.egnify.io
#   only:
#     - uat

