# Default values for helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: registry.gitlab.com/lyra-egnify/lms-sso/development
  tag: latest
  pullPolicy: Always
  pullSecrets: gitlab-registry-pull-secret

projectEnv:
  nodeEnv: "production"
  mongodbUri: "mongodb://hydra:AkdjsAIYHjk87y23l1m2klRrtyhjnmrti92w33@35.200.234.132:27017/tenantregistry-lms-dev"
  svcSettings: "http://settings-dev-lms.dev.svc.cluster.local"
  svcTest: "http://test-management-dev-lms.dev.svc.cluster.local"
  jwtSecret: "KAJDK656kllksklfmFGDFGS765ujh765T6GHAJDSjjjkjiursrda"
  mailjetApiKey: "a1fb4988b5a359099061d2cb8aebc80d"
  mailjetApiSecretkey: "2fc962b7e3aae82acee17b355fb9de2d"
  mailjetApiSecretkey: "2fc962b7e3aae82acee17b355fb9de2d"
  apiEgnifyIoUrl: "https://accounts.dev.lms.egnify.io"
  curxParserUrl: "https://crux-parser-v1.egnify.com"
  celeryBrokerUrl: "redis://:vvqfBAUfPI@redis-master.dev.svc.cluster.local:6379/0"
  celeryResultBackend: "redis://:vvqfBAUfPI@redis-master.dev.svc.cluster.local:6379/0"
  hostNameForAccounts: "accounts.dev.lms.egnify.io"
  commonHost: ".egnify.io"
  QUEUE_NS: 'lms-dev-mq'
  emailService: "gmail"
  emailHost: "smtp.gmail.com"
  emailUser: "support@egnify.com"
  emailPass: "$dew$008"

service:
  name: sso-lms-dev
  tier: backend
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - accounts.dev.lms.egnify.io
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "40M"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  tls:
    - secretName: lms-sso-tls-dev
      hosts:
        - accounts.dev.lms.egnify.io
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
