# Default values for helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: asia.gcr.io/egnify-product/hydra-ui-multi
  tag: v0.1.2
  pullPolicy: IfNotPresent
  # pullSecrets: registrypullsecret

projectEnv:
  nodeEnv: "production"
  mongodbUri: "mongodb://localhost:27017/china-dev"
  jwtSecret: "KAJDK656kllksklfmFGDFGS765ujh765T6GHAJDSjjjkjiursrda"
  mailjetApiKey: "a1fb4988b5a359099061d2cb8aebc80d"
  mailjetApiSecretkey: "2fc962b7e3aae82acee17b355fb9de2d"
  mailjetApiSecretkey: "2fc962b7e3aae82acee17b355fb9de2d"
  apiEgnifyIoUrl: "https://multi.hydra.egnify.io"

service:
  name: dev-hydra
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - luke.hydra.egnify.io
    - leia.hydra.egnify.io
    - solo.hydra.egnify.io
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/client-body-buffer-size: 40M
    kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    - secretName: chart-example-tls
      hosts:
        - luke.hydra.egnify.io
        - leia.hydra.egnify.io
        - solo.hydra.egnify.io
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
